#!/bin/bash
#
#       Extract genotypes for GRM
#
#SBATCH --job-name=<JOB_NAME>
#SBATCH --account=<ACCOUNT_NAME>
#SBATCH --mem-per-cpu=2048
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=2:00:00

set -o errexit
set -o pipefail
set -o nounset

# -----------------------------
# Input arguments
# -----------------------------
# $1 = input directory containing PLINK binary files
# $2 = input PLINK filename prefix (without .bed/.bim/.fam)
# $3 = output directory
# $4 = path to SNP list file for GRM extraction

IN_DIR="$1"
IN_FILE="$2"
OUT_DIR="$3"
SNPLIST="$4"

BINARY_FILE="${IN_DIR}/${IN_FILE}"

# Load PLINK
module load PLINK/1.09b6.16

# Extract genotypes
plink \
  --cow \
  --const-fid 0 \
  --extract "${SNPLIST}" \
  --bfile "${BINARY_FILE}" \
  --make-bed \
  --out "${OUT_DIR}/grm_geno_set"
