#!/bin/bash
#SBATCH --job-name=extract_snps
#SBATCH --account=<ACCOUNT_NAME>
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=4:00:00
#SBATCH --error=extract_snps.err

set -o errexit
set -o pipefail
set -o nounset

# -----------------------------
# User-defined input paths
# -----------------------------
DATADIR="<PATH_TO_PLINK_BINARY>"       # Input PLINK binary files directory/prefix
DISCOVERY_ID="<PATH_TO_IID_FILE>"      # Sample list file (IID.tsv)
TARGET_SNPS="<PATH_TO_SNP_LIST>"       # SNPs to extract, e.g., 50k.allchr.snplist
OUT_DIR="<OUTPUT_DIRECTORY>"           # Directory to save extracted SNPs

# Number of threads
THREADS=16

module load PLINK/1.09b6.16

# Extract target SNPs
plink --cow \
      --bfile "${DATADIR}" \
      --keep "${DISCOVERY_ID}" \
      --extract "${TARGET_SNPS}" \
      --threads "${THREADS}" \
      --make-bed \
      --out "${OUT_DIR}/TargetSNPs"
